# Generated by Django 4.1.7 on 2023-09-26 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPIF', models.CharField(max_length=255, verbose_name='ПіП Батьків')),
                ('passport_series_f', models.CharField(max_length=10, verbose_name='Паспорт батьків серія')),
                ('passport_number_f', models.CharField(max_length=20, verbose_name='Паспорт батьків номер')),
                ('passport_issued_f', models.CharField(max_length=255, verbose_name='Паспорт батьків виданий')),
            ],
            options={
                'verbose_name': 'Батьки Студентів',
                'verbose_name_plural': 'Студенти',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPI', models.CharField(max_length=255, verbose_name='ПІП')),
                ('date_of_birth', models.DateField(verbose_name='Дата народження')),
                ('group', models.CharField(max_length=10, verbose_name='Група')),
                ('street', models.CharField(max_length=255, verbose_name='Вулиця')),
                ('house', models.CharField(max_length=10, verbose_name='Дім')),
                ('room', models.CharField(max_length=10, verbose_name='Кімната')),
                ('hostel', models.PositiveSmallIntegerField(verbose_name='Гуртожиток')),
                ('faculty', models.CharField(max_length=255, verbose_name='Факультет')),
                ('course', models.IntegerField(choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс'), (5, '5 курс')], verbose_name='Курс')),
                ('bloc', models.CharField(max_length=10, verbose_name='Блок')),
                ('learning_from', models.PositiveSmallIntegerField(verbose_name='Початок навчання')),
                ('training_to', models.PositiveSmallIntegerField(verbose_name='Закінчення')),
                ('passport_series', models.CharField(max_length=10, verbose_name='Паспорт серія')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Паспорт номер')),
                ('passport_issued', models.CharField(max_length=255, verbose_name='Паспорт виданий')),
                ('identification_code', models.CharField(max_length=20, verbose_name='Індифікаційний код')),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settlement.studentparens', verbose_name='Батьки')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
    ]
