# Generated by Django 4.1.7 on 2023-09-27 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settlement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_number', models.CharField(max_length=10, verbose_name='Номер гуртожитка')),
                ('residents', models.CharField(max_length=255, verbose_name='Хто проживає')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Мобільний номер')),
            ],
            options={
                'verbose_name': 'Гуртожиток',
                'verbose_name_plural': 'Гуртожитки',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settlement.studentparens', verbose_name='Батьки'),
        ),
    ]
